# Generated by Django 2.2.6 on 2023-01-05 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20230105_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.SlugField(help_text='Введите адрес группы', max_length=100, unique=True, verbose_name='Адрес группы (slug)'),
        ),
    ]
