# Generated by Django 2.2.16 on 2023-02-02 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_auto_20230202_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, help_text='Введите название поста', max_length=150, null=True, verbose_name='Заголовок'),
        ),
    ]
