# Generated by Django 2.2.16 on 2023-02-05 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_auto_20230205_1154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like',
            options={'verbose_name': ('Лайк',), 'verbose_name_plural': 'Лайки'},
        ),
    ]
