# Generated by Django 2.2.16 on 2023-02-05 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0024_auto_20230205_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='value',
            field=models.CharField(choices=[('Нравится', 'Нравится'), ('Не нравится', 'Не нравится')], default='Нравится', max_length=10, verbose_name='Значение'),
        ),
    ]
