# Generated by Django 2.2.16 on 2023-02-10 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0027_auto_20230209_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(help_text='Введите новое фильтруемое слово', max_length=50, unique=True, verbose_name='"Плохие" слова')),
            ],
        ),
    ]
