# Generated by Django 2.2.16 on 2023-02-10 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0028_badwords'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='badwords',
            options={'verbose_name': ('"Плохое" слово',), 'verbose_name_plural': '"Плохие" слова'},
        ),
    ]
