# Generated by Django 2.2.16 on 2023-02-13 08:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0030_auto_20230213_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='liked',
            field=models.ManyToManyField(blank=True, default=None, related_name='liked_by', to=settings.AUTH_USER_MODEL, verbose_name='Лайкнули'),
        ),
    ]
