# Generated by Django 2.2.16 on 2023-02-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0032_auto_20230213_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='value',
            field=models.CharField(choices=[('Нравится', 'Нравится'), ('Не нравится', 'Не нравится')], default='Нравится', max_length=11, verbose_name='Значение'),
        ),
    ]
