"""
Django settings for yatube project.

Generated by 'django-admin startproject' using Django 2.2.19.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'i3an-a^x*b(8uo&f+h-y=^y%a=^_*2^+c_eu^juw61wpw$y%*+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    '*',
    'trsv.codeanywhere.com',
    'localhost',
    '127.0.0.1',
    '[::1]',
    'testserver',
]

INTERNAL_IPS = [
    '127.0.0.1',
]

# Application definition

INSTALLED_APPS = [
    'core.apps.CoreConfig',
    'posts.apps.PostsConfig',
    'users.apps.UsersConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'sorl.thumbnail',
    'debug_toolbar',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'debug_toolbar.middleware.DebugToolbarMiddleware',
]

ROOT_URLCONF = 'yatube.urls'

# Путь к директории с шаблонами вынесен в переменную:
TEMPLATES_DIR = os.path.join(BASE_DIR, 'templates')
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Добавлено: Искать шаблоны на уровне проекта
        'DIRS': [TEMPLATES_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # Добавлен контекст-процессор
                'core.context_processors.year.year',
            ],
        },
    },
]

WSGI_APPLICATION = 'yatube.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

LOGIN_URL = '/auth/login/'
LOGIN_REDIRECT_URL = '/auth/profile/'


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
CSRF_FAILURE_VIEW = 'core.views.csrf_failure'
POSTS_PER_PAGE = 10
TEXT_CROP = 15
# DEFAULT_TITLE_TEXT_CROP = 30
TEST_ID = 1
LOGIN_REDIRECT_URL = 'posts:index'

# names
INDEX = 'posts:index'
PROFILE = 'posts:profile'
POST_DETAIL = 'posts:post_detail'
GROUP_LIST = 'posts:group_list'
POST_CREATE = 'posts:post_create'
POST_EDIT = 'posts:post_edit'
SIGNUP = 'users:signup'
ADD_COMMENT = 'posts:add_comment'
FOLLOW = 'posts:profile_follow'
FOLLOW_INDEX = 'posts:follow_index'
UNFOLLOW = 'posts:profile_unfollow'

# urls
URL_INDEX = '/'
URL_PROFILE = '/profile/Author/'
URL_POST_DETAIL = '/posts/1/'
URL_GROUP_LIST = '/group/test-slug/'
URL_POST_CREATE = '/create/'
URL_POST_EDIT = '/posts/1/edit/'
URL_UNEXSISTING_PAGE = '/unexsisting_page/'
URL_LOGIN_PAGE = '/auth/login/'
URL_ABOUT_AUTHOR = '/about/author/'
URL_ABOUT_TECH = '/about/tech/'
URL_REDIRECT_FROM_CREATE = '/auth/login/?next=/create/'
URL_REDIRECT_FROM_EDIT = '/auth/login/?next=/posts/1/edit/'
URL_REDIRECT_FROM_COMMENT = '/auth/login/?next=/posts/1/comment/'
URL_REDIRECT_FROM_FOLLOW = '/auth/login/?next=/posts/1/follow/'
URL_REDIRECT_FOR_NOT_AUTHOR = '/profile/Not_Author/'
URL_SIGNUP = '/auth/signup/'

# htmls
HTML_INDEX = 'posts/index.html'
HTML_PROFILE = 'posts/profile.html'
HTML_POST_DETAIL = 'posts/post_detail.html'
HTML_GROUP_LIST = 'posts/group_list.html'
HTML_POST_CREATE = 'posts/create_post.html'
HTML_POST_EDIT = 'posts/create_post.html'
HTML_SIGNUP = 'users/signup.html'
HTML_404 = 'core/404.html'
HTML_403 = 'core/403csrf.html'
HTML_FOLLOW = 'posts/follow.html'

# EMAIL_BACKEND = 'django.core.mail.backends.filebased.EmailBackend'
# EMAIL_FILE_PATH = os.path.join(BASE_DIR, 'sent_emails')

# Отправка писем Google-почтой (Работает на pythonanywhere.com)
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_USE_SSL = False
# EMAIL_HOST_USER = 'root.srv.mail@gmail.com'
# EMAIL_HOST_PASSWORD = 'lzzorwbuwnljusst'
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# Отправка писем Яндекс-почтой (Не работает на pythonanywhere.com)
RECIPIENT_ADDRESS = 'trsv.dev@yandex.ru'
EMAIL_HOST = 'smtp.yandex.ru'
EMAIL_PORT = 465
EMAIL_USE_SSL = True
DEFAULT_FROM_EMAIL = 'trsv.dev@yandex.ru'
EMAIL_HOST_USER = 'trsv.dev@yandex.ru'
EMAIL_HOST_PASSWORD = 'hzitlzdryltagtly'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
